### ISSUE TITLE
IDN names in notification emails

### ISSUE THREAD

**Issue by huguei** [rafaeljusto/shelter#130]
Hi. I wonder if is it possible to change the current look of IDN domain names in notification emails sent by the system. Right now in the subject and body of the message is shown the "punycode" encoding, but it's recommended to display the unicode one, with UTF8 encoding.
(You can use as example the name "sebastián.cl", which is misconfigured right now!)

> [...]
> Subject: Misconfiguration on domain xn--sebastin-fza.cl.
> 
> Dear Sir/Madam,
> 
> During our periodically domain verification, a configuration problem was detected with the
> domain xn--sebastin-fza.cl..
> [...]

Thanks!

**Comment by rafaeljusto** [comment]
Yes, it is possible, but we probably need to follow the [RFC 1342](https://tools.ietf.org/html/rfc1342). I will take a look on this!

**Comment by rafaeljusto** [comment]
New version released (0.3-29)
