### ISSUE TITLE
Wrong description to DS.TIMEOUT error on Notification template

### ISSUE THREAD

**Issue by huguei** [rafaeljusto/shelter#131]
Hi. In the notification template (en-US version) I think there's a wrong description of the TIMEOUT error in DS case. The wiki says "DNSKEY Network timeout", but the template text reads:

> {{if dsStatusEq $ds.LastStatus "TIMEOUT"}}
> - DS with keytag {{$ds.Keytag}} isn't answering the DNS requests.
>   Please check your firewalls and DNS server and make sure that the service is up...

I think it'll be more precise to say:

> - DNSKEY with keytag {{$ds.Keytag}} couldn't be retrieved (network timeout)

Thanks,

Hugo

**Comment by rafaeljusto** [comment]
Hi Hugo,

Thank you for detecting the message problem. :smile:
Release 0.3-30 contains the fix!

Rafael
